MockExams/Models/Equipment.cs
namespace MockExams.Models
{
    public class Equipment
    {
        
            public int EquipmentId { get; set; }

            public string Name { get; set; }
            public string Description { get; set; }

            public int QuantityAvailable { get; set; }
            public decimal Price { get; set; }
            public bool IsAvailable { get; set; }

            // Equipment can appear in many equipment bookings
            public ICollection<BookingEquipment>? BookingEquipment { get; set; }
        
    
    }
}

MockExams/Controllers/BookingEquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MockExams.Data;
using MockExams.Models;

namespace MockExams.Controllers
{
    public class BookingEquipmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookingEquipmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BookingEquipments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BookingEquipment.Include(b => b.Equipment);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BookingEquipments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingEquipment = await _context.BookingEquipment
                .Include(b => b.Equipment)
                .FirstOrDefaultAsync(m => m.BookingEquipmentId == id);
            if (bookingEquipment == null)
            {
                return NotFound();
            }

            return View(bookingEquipment);
        }
        [Authorize(Roles = "Admin,Customer" )]
        // GET: BookingEquipments/Create
        public IActionResult Create(int EquipmentId)
        {
            ViewBag.EquipmentId = EquipmentId;
            return View();
        }

        // POST: BookingEquipments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("BookingEquipmentId,EquipmentId,Quantity,IsAvailable")] BookingEquipment bookingEquipment)
        {
          var equipment = await _context.Equipment.FindAsync(bookingEquipment.EquipmentId);
            if (equipment == null)
            {
                return View(bookingEquipment);
            }
            bookingEquipment.Equipment = equipment;
            ModelState.Remove("Equipment");

            if (ModelState.IsValid)
            {
                _context.Add(bookingEquipment);
                await _context.SaveChangesAsync();
                equipment.IsAvailable = false;
                return RedirectToAction(nameof(Index));
            }
            ViewBag.EquipmentId = bookingEquipment;
            return View(bookingEquipment);
        }

        // GET: BookingEquipments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingEquipment = await _context.BookingEquipment.FindAsync(id);
            if (bookingEquipment == null)
            {
                return NotFound();
            }
            ViewData["EquipmentId"] = new SelectList(_context.Set<Equipment>(), "EquipmentId", "EquipmentId", bookingEquipment.EquipmentId);
            return View(bookingEquipment);
        }

        // POST: BookingEquipments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("BookingEquipmentId,EquipmentId,Quantity,IsAvailable")] BookingEquipment bookingEquipment)
        {
            if (id != bookingEquipment.BookingEquipmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookingEquipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingEquipmentExists(bookingEquipment.BookingEquipmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EquipmentId"] = new SelectList(_context.Set<Equipment>(), "EquipmentId", "EquipmentId", bookingEquipment.EquipmentId);
            return View(bookingEquipment);
        }
        [Authorize(Roles = "Staff")]
        // GET: BookingEquipments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingEquipment = await _context.BookingEquipment
                .Include(b => b.Equipment)
                .FirstOrDefaultAsync(m => m.BookingEquipmentId == id);
            if (bookingEquipment == null)
            {
                return NotFound();
            }

            return View(bookingEquipment);
        }

        // POST: BookingEquipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Staff")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookingEquipment = await _context.BookingEquipment.FindAsync(id);
            if (bookingEquipment != null)
            {
                _context.BookingEquipment.Remove(bookingEquipment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingEquipmentExists(int id)
        {
            return _context.BookingEquipment.Any(e => e.BookingEquipmentId == id);
        }
    }
}

MockExams/Controllers/EquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MockExams.Data;
using MockExams.Models;

namespace MockExams.Controllers
{
    public class EquipmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EquipmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Equipments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Equipment.ToListAsync());
        }

        // GET: Equipments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment
                .FirstOrDefaultAsync(m => m.EquipmentId == id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // GET: Equipments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Equipments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create([Bind("EquipmentId,Name,Description,QuantityAvailable,Price,IsAvailable")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(equipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipment);
        }

        // GET: Equipments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment.FindAsync(id);
            if (equipment == null)
            {
                return NotFound();
            }
            return View(equipment);
        }

        // POST: Equipments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Edit(int id, [Bind("EquipmentId,Name,Description,QuantityAvailable,Price,IsAvailable")] Equipment equipment)
        {
            if (id != equipment.EquipmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(equipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EquipmentExists(equipment.EquipmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipment);
        }

        // GET: Equipments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment
                .FirstOrDefaultAsync(m => m.EquipmentId == id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // POST: Equipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var equipment = await _context.Equipment.FindAsync(id);
            if (equipment != null)
            {
                _context.Equipment.Remove(equipment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EquipmentExists(int id)
        {
            return _context.Equipment.Any(e => e.EquipmentId == id);
        }
    }
}

MockExams/Views/Equipments/Create.cshtml
@model MockExams.Models.Equipment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Equipment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantityAvailable" class="control-label"></label>
                <input asp-for="QuantityAvailable" class="form-control" />
                <span asp-validation-for="QuantityAvailable" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MockExams/Views/Equipments/Delete.cshtml
@model MockExams.Models.Equipment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Equipment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantityAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantityAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EquipmentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MockExams/Views/Equipments/Details.cshtml
@model MockExams.Models.Equipment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Equipment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuantityAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuantityAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.EquipmentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MockExams/Views/Equipments/Edit.cshtml
@model MockExams.Models.Equipment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Equipment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EquipmentId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantityAvailable" class="control-label"></label>
                <input asp-for="QuantityAvailable" class="form-control" />
                <span asp-validation-for="QuantityAvailable" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MockExams/Views/Equipments/Index.cshtml
@model IEnumerable<MockExams.Models.Equipment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuantityAvailable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuantityAvailable)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAvailable)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EquipmentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.EquipmentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.EquipmentId">Delete</a>       |
                 <a asp-controller="BookingEquipments" asp-action="Create" asp-route-EquipmentId="@item.EquipmentId">Book Now :)</a> 
            </td>
        </tr>
}
    </tbody>
</table>

<